<?php
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

echo "--- simulating broadcast ---\n";
try {
    DB::beginTransaction();
    $adminId = 1; // Assuming 1 exists
    
    // 1. Create Notif
    $notifId = DB::table('ms_notifikasi')->insertGetId([
        'AdminID' => $adminId,
        'TipeNotifikasi' => 'System',
        'JudulNotifikasi' => 'Test Notification ' . time(),
        'IsiNotifikasi' => 'This is a test notification generated by script.'
    ]);
    echo "Created Notif ID: $notifId\n";
    
    // 2. Target User (Assume ID 1 is the admin/user viewing)
    $targetId = 1; 

    // 3. Insert
    DB::table('tr_pengirimannotifikasi')->insert([
        'NotifikasiID' => $notifId,
        'PenggunaTargetID' => $targetId,
        'WaktuKirim' => Carbon::now(),
        'StatusKirim' => 'Sent'
    ]);
    echo "Inserted into tr_pengirimannotifikasi for User $targetId\n";

    DB::commit();
    echo "SUCCESS\n";
} catch (\Exception $e) {
    DB::rollBack();
    echo "FAILED: " . $e->getMessage() . "\n";
}
